// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockTraderBackend.Data;

#nullable disable

namespace StockTraderBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockTraderBackend.Assets.PriceBar.Models.PriceBar", b =>
                {
                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<string>("Timeframe")
                        .HasColumnType("text");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(20,6)");

                    b.HasKey("SymbolId", "Timeframe", "Ts");

                    b.HasIndex("SymbolId", "Ts");

                    b.ToTable("price_bars", (string)null);
                });

            modelBuilder.Entity("StockTraderBackend.Assets.Symbols.Model.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastBackfillAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastBackfillSuccessUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSplitDetectedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSplitScanUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NeedsBackfill")
                        .HasColumnType("boolean");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("symbols", (string)null);
                });

            modelBuilder.Entity("StockTraderBackend.Chat.ChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("StockTraderBackend.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatHistoryId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("StockTraderBackend.Holdings.Holding", b =>
                {
                    b.Property<Guid>("holdingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("avgBuyPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("portfolioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("quantity")
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("holdingId");

                    b.HasIndex("portfolioId");

                    b.HasIndex("ticker");

                    b.ToTable("holdings", (string)null);
                });

            modelBuilder.Entity("StockTraderBackend.MarketData.StockSplits.Models.StockSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DetectedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("MassiveSplitId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SplitFactor")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("SplitFrom")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("SplitTo")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MassiveSplitId")
                        .IsUnique()
                        .HasFilter("\"MassiveSplitId\" IS NOT NULL");

                    b.HasIndex("SymbolId", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("stock_splits", (string)null);
                });

            modelBuilder.Entity("StockTraderBackend.News.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("StockTraderBackend.News.Models.FavoriteArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FavoritedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ArticleId")
                        .IsUnique();

                    b.ToTable("favorite_articles", (string)null);
                });

            modelBuilder.Entity("StockTraderBackend.PortfolioValueTracking.PortfolioSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PortfolioSnapshots");
                });

            modelBuilder.Entity("StockTraderBackend.PortfolioValueTracking.PortfolioSnapshotHolding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PortfolioSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PriceAtSnapshot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Shares")
                        .HasColumnType("numeric");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioSnapshotId");

                    b.ToTable("PortfolioSnapshotHoldings");
                });

            modelBuilder.Entity("StockTraderBackend.Portfolios.Portfolio", b =>
                {
                    b.Property<Guid>("portfolioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("cashBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(1000000m);

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Default");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("portfolioId");

                    b.HasIndex("userId");

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("StockTraderBackend.Trades.Trade", b =>
                {
                    b.Property<Guid>("tradeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("executedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("portfolioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("priceAtTrade")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("quantity")
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("totalValue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("tradeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("tradeId");

                    b.HasIndex("portfolioId");

                    b.HasIndex("ticker");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("StockTraderBackend.Users.User", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("username")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Default");

                    b.HasKey("userId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StockTraderBackend.Watchlist.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("watchlists", (string)null);
                });

            modelBuilder.Entity("StockTraderBackend.Watchlist.WatchlistStock", b =>
                {
                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("uuid");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("WatchlistId", "SymbolId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("WatchlistId");

                    b.ToTable("watchlist_stocks", (string)null);
                });

            modelBuilder.Entity("StockTraderBackend.Assets.PriceBar.Models.PriceBar", b =>
                {
                    b.HasOne("StockTraderBackend.Assets.Symbols.Model.Symbol", "Symbol")
                        .WithMany("PriceBars")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("StockTraderBackend.Chat.ChatMessage", b =>
                {
                    b.HasOne("StockTraderBackend.Chat.ChatHistory", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockTraderBackend.Holdings.Holding", b =>
                {
                    b.HasOne("StockTraderBackend.Portfolios.Portfolio", "portfolio")
                        .WithMany("holdings")
                        .HasForeignKey("portfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("portfolio");
                });

            modelBuilder.Entity("StockTraderBackend.MarketData.StockSplits.Models.StockSplit", b =>
                {
                    b.HasOne("StockTraderBackend.Assets.Symbols.Model.Symbol", "Symbol")
                        .WithMany("StockSplits")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("StockTraderBackend.News.Models.FavoriteArticle", b =>
                {
                    b.HasOne("StockTraderBackend.News.Models.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockTraderBackend.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockTraderBackend.PortfolioValueTracking.PortfolioSnapshotHolding", b =>
                {
                    b.HasOne("StockTraderBackend.PortfolioValueTracking.PortfolioSnapshot", null)
                        .WithMany("Holdings")
                        .HasForeignKey("PortfolioSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockTraderBackend.Portfolios.Portfolio", b =>
                {
                    b.HasOne("StockTraderBackend.Users.User", "user")
                        .WithMany("portfolios")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("StockTraderBackend.Trades.Trade", b =>
                {
                    b.HasOne("StockTraderBackend.Portfolios.Portfolio", "portfolio")
                        .WithMany("trades")
                        .HasForeignKey("portfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("portfolio");
                });

            modelBuilder.Entity("StockTraderBackend.Watchlist.Watchlist", b =>
                {
                    b.HasOne("StockTraderBackend.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockTraderBackend.Watchlist.WatchlistStock", b =>
                {
                    b.HasOne("StockTraderBackend.Assets.Symbols.Model.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockTraderBackend.Watchlist.Watchlist", "Watchlist")
                        .WithMany("Stocks")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("StockTraderBackend.Assets.Symbols.Model.Symbol", b =>
                {
                    b.Navigation("PriceBars");

                    b.Navigation("StockSplits");
                });

            modelBuilder.Entity("StockTraderBackend.Chat.ChatHistory", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("StockTraderBackend.PortfolioValueTracking.PortfolioSnapshot", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("StockTraderBackend.Portfolios.Portfolio", b =>
                {
                    b.Navigation("holdings");

                    b.Navigation("trades");
                });

            modelBuilder.Entity("StockTraderBackend.Users.User", b =>
                {
                    b.Navigation("portfolios");
                });

            modelBuilder.Entity("StockTraderBackend.Watchlist.Watchlist", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
